name: Update career paths of drafted players

on:
  schedule:
    - cron: '0 0 28 * *'    # Run on the 28th of every month at midnight UTC

  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  update_career_paths:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to update career paths of drafted players
        run: python dataset_creation.py

      - name: Commit and push updated career path data
        run: |
          git config --global user.name "KMCSquared"
          git config --global user.email "97289825+kmcsquared@users.noreply.github.com"
          git add data
          git commit -m "Update career path data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication